services:
    dovecot:
        build:
            context: ./dovecot
        hostname: dovecot.k8s-mail-internal.svc.cluster.local
        environment:
        - INITIALIZE_USER=me@k8s-mail.com
        ports:
        # standard IMAPS port
        - 993:993
        # the submission service is run by Dovecot, not Postfix
        - 587:587
        # Standard IMAP port, note that this is not used by Dovecot. However, it is
        # exposed to confirm with a test that no service is running
        - 143:143
        # The LMTP port
        - 24:24
        volumes:
        - ${PWD}/dovecot/dovecot.conf:/etc/dovecot/dovecot.conf
        - ${PWD}/volumes:/etc/dovecot/secrets
    postfix:
        build:
            context: ./postfix
        hostname: postfix.default.svc.cluster.local
        depends_on:
        - dovecot
        volumes:
        - ${PWD}/postfix/main.cf:/etc/postfix/main.cf
        - ${PWD}/postfix/virtual:/etc/postfix/virtual
        ports:
            - 25:25
